language: go
go:
- stable
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
- dep ensure
before_deploy:
- go get github.com/mitchellh/gox
- mkdir releases
- gox -osarch="linux/amd64 darwin/amd64"
  -output="releases/{{.Dir}}_`git describe --tags --abbrev=0`_{{.OS}}_{{.Arch}}/{{.Dir}}"
  -ldflags "-X main.Version=`git describe --tags --abbrev=0`"
- find releases -maxdepth 2 -mindepth 2 -type f -exec bash -c 'tar -cvzf "$(dirname
  {}).tar.gz" -C "$(dirname {})" $(basename {})' \;
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file: "releases/*.tar.gz"
  file_glob: true # enables wildcards in file names
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
